name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  prelint-checks:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: pre-lint-checks
      run: |
        - docker pull hadolint/hadolint
        - docker run hadolint/hadolint hadolint --version
