name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  prelint-checks:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Hadolint Dockerfile
      uses: burdzwastaken/hadolint-action@master

