name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  prelint-checks:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Hadolint Dockerfile
      run: |
        docker pull hadolint/hadolint
        docker run hadolint/hadolint hadolint --version
        ls -al samples/gradle-java-jdk8-x-jre11-custom/Dockerfile
        docker run --rm -i hadolint/hadolint < samples/gradle-java-jdk8-x-jre11-custom/Dockerfile
        
        

